### PR TITLE
WIP: Adafruit nRF52 Feather Integration

### PR DESCRIPTION
**Pull request by jeremypoulter**
**WORK IN PROGRESS/REQUEST FOR COMMENT**

I have been working on integrating Adafruit's nRF52 SDK into Platform IO to use as an alternative to @sandeepmistry's mainly due to the support for Central mode. I have got to a point where I can compile (but still have a linker issue) but before I go much further down the road I wanted to get some input on if this is the the right direction.

My current thinking is that this will have to exist as a separate platform to the current one as I can not see an easy way of referencing multiple arduino cores, but please let me know if there is.

### CODE REVIEW

**Comment by cujomalainey** [comment]
If I'm reading your code right, I think you are using the standard linker script, not the one provided by adafruit `bluefruit52_s132_v201.ld` that might be part of your problem.

**Comment by jeremypoulter** [comment]
I think I am using the Adafruit linker script, it is the include from from that script is erroring, but thanks for the suggestion.

**Comment by jeremypoulter** [comment]
Copied from #8 for completeness:

Managed to get back to this. I have the firmware building and I can manually upload it using the `nrfutil` package:

```
nrfutil dfu genpkg --dev-type 0x0052 --sd-req 0x00A5 --application .pioenvs/bluefruit_nrf52/firmware.hex .pioenvs/bluefruit_nrf52/firmware.zip
nrfutil dfu serial -pkg .pioenvs/bluefruit_nrf52/firmware.zip -p /dev/ttyUSB0 -b 115200
```

So basically the remaining tasks are:
- [ ] Change to HTTPS Git links
- [ ] Integrate `nrfutil` and upload over serial - Any pointer?
- [ ] Upload via programmer, J-Link/nrfprog
- [ ] flash bootloader

FYI see https://github.com/jeremypoulter/platformio-examples for an example

**Comment by jeremypoulter** [comment]
Getting quite close now, I don't think it is possible to upload via a programmer is using the bootloader/softdevice, but the serial DFU works quite well.

I have figured out the nrfutil tool download, same as any other package you can put a Git url in place pf a version, just need to figure out how to install in the PIO virtual env:

```
pip install -r requirements.txt
python setup.py install
```

@ivankravets Any help you can offer?

**Comment by ivankravets** [comment]
@jeremypoulter Did you test `upload_protocol = nrfjprog`?

**Comment by jeremypoulter** [comment]
Yeah, I need to do some more research but I think nrfutil/DFU performs some
additional steps over and above just flashing the binary.

Plus there are additional benefits in the Bootloader/DFU mechanism as it
can be used for OTA updating the firmware so I think it is of value to
integrate.

**Comment by jeremypoulter** [comment]
Have added support for uploading via the standard J-Link drivers, bit clunky but works ok. There is a ticket (adafruit/Adafruit_nRF52_Arduino#133) to add this feature to the Arduino IDE core so hopefully this will yield a better solution.

@ivankravets this is now basically meating my requirements so the time I can spend on it will be limited. For what it is worth I did this work not to get support for the Feather as such but to uplift to SD132 v5. IMHO this core looks to have more active development and I am currently using with a non-feather board. Would it help to update the NRF52 DK config?

**Comment by jeremypoulter** [comment]
Closing in favour of newer #23

**Pull request closed without merging**
